apiVersion: apps/v1
kind: Deployment
metadata:
  name: bobo
  labels:
    app: bobo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bobo
  template:
    metadata:
      labels:
        app: bobo
    spec:
      containers:
      - name: bobo
        image: quay.io/cooloo9871/bobo
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: bobo
spec:
  selector:
    app: bobo
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
